name: Merge and release to staging
permissions:
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      release_tag_task_url:
          description: "Release Tag task URL(e.g. https://app.clickup.com/t/1**/W*-*)"
          required: true
      skip_pending_checks:
        description: "Skip waiting for pull request checks"
        type: boolean
        required: false

concurrency:
  group: release_automation_group

jobs:
  release_issues:
    permissions: write-all
    # Reduced timeout from 10 hours to 2 hours, which should be sufficient
    timeout-minutes: 120
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Release issues in Derivatives Trader
        uses: binary-com/fe-toolbox@v0.0.2
        timeout-minutes: 60
        with:
          release_tag_task_url: ${{ inputs.release_tag_task_url }}
          platform: 'Deriv.app'
          config_path: ./.github/workflows/automationrc.json
          skip_pending_checks: ${{ inputs.skip_pending_checks }}
          CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
